### PR TITLE
Make makefile more robust and helpful

### PR DESCRIPTION
**Pull request by matthieu-foucault**
Rebasing changes merged in #59

### CODE REVIEW

**Comment by matthieu-foucault** [comment]
You closed instead of merging :cry: Was that intentional?

**Comment by wenzowski** [comment]
I meant to mark this continued elsewhere

**Comment by wenzowski** [comment]
but actually, I should have rebased & merged as-is

**Comment by matthieu-foucault** [comment]
Ok. fa0c76d  and 7abda2e haven't been merged in `feature/deploy` so you might want to cherry pick them there too :)

**Pull request closed without merging**
